version: 0.2
    
phases:   
  install:
    runtime-versions:
      nodejs: 14
      python: latest
      
  pre_build:
    commands:
      - npm install -g aws-cdk
      - npm install
      # - npm i aws-cdk@1.192.0
      # - cdk doctor -g --force
      - pip install -r requirements.txt 
      - node --version
      
  build:
    commands:
      - npm run build
      - echo Build started on `date`
      - cdk deploy
      
  post_build:
    commands:
      - echo Build completed on `date`