version: 0.2
    
phases:   
  install:
    runtime-versions:
      nodejs: 14
      
  pre_build:
    commands:
      - npm install -g aws-cdk
      
  build:
    commands:
      - echo Build started on `date`
      - cdk deploy
      
  post_build:
    commands:
      - echo Build completed on `date`